version: "3.5"
services:
  jenkins-master:
    depends_on:
      - jenkins-slave
      - sonarqube
    container_name: jenkins-master
    image: jenkins/jenkins:lts-alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  jenkins-slave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-slave
    ports:
      - "2233:2233"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    depends_on:
      - sonar-db
    container_name: sonarqube
    image: sonarqube:developer
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
     - sonarqube_data:/opt/sonarqube/data
     - sonarqube_logs:/opt/sonarqube/logs
     - sonarqube_extensions:/opt/sonarqube/extensions
  sonar-db:
    container_name: sonar-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
  