version: "3.5"
services:
  jenkins-master:
    depends_on:
      - jenkins-slave
      - sonarqube
    container_name: jenkins-master
    image: jenkins/jenkins:lts-alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  jenkins-slave:
    build:
      context: .
      dockerfile: Dockerfile_Jenkins_Slave
    container_name: jenkins-slave
    ports:
      - "2222:2222"
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
     - sonarqube_conf:/opt/sonarqube/conf
     - sonarqube_data:/opt/sonarqube/data
     - sonarqube_logs:/opt/sonarqube/logs
     - sonarqube_extensions:/opt/sonarqube/extensions
volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: